spring:
  application:
    name: global-config
  # Ortak veritabanı yapılandırması
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/musicgame
    username: postgres
    password: 9991509
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

# Ortak Eureka Client yapılandırması
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

# Ortak Actuator yapılandırması
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# JWT Token yapılandırması (tüm servisler tarafından kullanılır)
jwt:
  secret: musicGameSecretKey123456789012345678901234567890ABCDEFGHIJ
  expirationMs: 86400000  # 24 saat
  refreshExpirationMs: 604800000  # 7 gün 